;*******************************************************************
;*    Description : Using Timer0 and INT0 interrupt
;*    
;*******************************************************************
    
#include<p18f452.inc> 
CONFIG  WDT = OFF, OSCS=OFF, OSC=HS
ORG 0
GOTO MAIN

ORG 8
BTFSC INTCON,INT0IF ;HIGH PRIORITY INTERUPT 
BRA BTN_ISR
RETFIE
 
ORG 18
BTFSC INTCON,TMR0IF ;LOW PRIORITY INTERUPT
BRA BLINK_ISR
RETFIE

ORG 100
MAIN BCF TRISC,RC5
BCF TRISC,RC6
BSF TRISB,RB0
MOVLW B'00100000'
MOVWF PORTC

;TMR 0
BSF INTCON, TMR0IE
BSF RCON,IPEN
BCF INTCON2,TMR0IP 
MOVLW 06
MOVWF T0CON
MOVLW 0B3
MOVWF TMR0H
MOVLW 0B4
MOVWF TMR0L
BCF INTCON, TMR0IF
BSF INTCON,GIEH
BSF INTCON,GIEL
BSF T0CON,TMR0ON
 
 
BCF INTCON ,INT0IF
BSF INTCON, INT0IE
BCF INTCON2,RBPU
    
HERE GOTO HERE
 
BTN_ISR BSF TRISC,RC6
BCF INTCON,INT0IF
RETFIE
 
BLINK_ISR BCF T0CON,TMR0ON
  BTG PORTC,RC5
  BTG PORTC,RC6
  MOVLW 0B3
  MOVWF TMR0H
  MOVLW 0B4
  MOVWF TMR0L
  BCF INTCON, TMR0IF
  BSF T0CON,TMR0ON
  RETFIE

END